import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route("health", "routes/health.ts"),
  route("auth", "routes/auth.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password/:token", "routes/reset-password.tsx"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("api/check-username", "routes/api.check-username.ts"),
  route("api/create-username", "routes/api.create-username.ts"),
  route("api/contact", "routes/api.contact.ts"),
  route("api/user/ratings", "routes/api.user.ratings.ts"),
  route("api/user/ratings/:id", "routes/api.user.ratings.$id.ts"),
  route("api/user/comments", "routes/api.user.comments.ts"),
  route("api/user/comments/:id", "routes/api.user.comments.$id.ts"),
  route("api/user/reports", "routes/api.user.reports.ts"),
  layout("routes/site.tsx", [
    index("routes/home.tsx"),
    route("movie/:slug", "routes/movie.$slug.tsx"),
    route("tv/:slug", "routes/tv.$slug.tsx"),
    route("short/:slug", "routes/short.$slug.tsx"),
    route("movie/:slug/opengraph-image", "routes/og.movie.$slug.ts"),
    route("tv/:slug/opengraph-image", "routes/og.tv.$slug.ts"),
    route("short/:slug/opengraph-image", "routes/og.short.$slug.ts"),
    route("movies-and-tv", "routes/movies-and-tv.tsx"),
    route("scoreboard", "routes/scoreboard.tsx"),
    route("discussions", "routes/discussions.tsx"),
    route("reviews", "routes/reviews.tsx"),
    route("reviews/:id", "routes/reviews.$id.tsx"),
    route("members/:username", "routes/members.$username.tsx"),
    route("about", "routes/about.tsx"),
    route("privacy", "routes/privacy.tsx"),
    route("terms", "routes/terms.tsx"),
    route("contact", "routes/contact.tsx"),
  ]),
] satisfies RouteConfig;
