import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route("health", "routes/health.ts"),
  route("media/*", "routes/media.tsx"),
  route("auth", "routes/auth.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password/:token", "routes/reset-password.tsx"),
  route("account-claim", "routes/account-claim.tsx"),
  route("api/account-claim", "routes/api.account-claim.ts"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("api/check-username", "routes/api.check-username.ts"),
  route("api/create-username", "routes/api.create-username.ts"),
  route("api/contact", "routes/api.contact.ts"),
  route("api/user/ratings", "routes/api.user.ratings.ts"),
  route("api/user/ratings/:id", "routes/api.user.ratings.$id.ts"),
  route("api/user/comments", "routes/api.user.comments.ts"),
  route("api/user/comments/:id", "routes/api.user.comments.$id.ts"),
  route("api/user/reports", "routes/api.user.reports.ts"),
  route("api/admin/users", "routes/api.admin.users.tsx"),
  route("api/admin/users/:id/admin-role", "routes/api.admin.users.$id.admin-role.tsx"),
  route("api/admin/users/:id/regular-role", "routes/api.admin.users.$id.regular-role.tsx"),
  route("api/admin/user-ratings", "routes/api.admin.user-ratings.tsx"),
  route("api/admin/user-ratings/:id/flag", "routes/api.admin.user-ratings.$id.flag.tsx"),
  route("api/admin/user-ratings/:id/restrict", "routes/api.admin.user-ratings.$id.restrict.tsx"),
  route("api/admin/comments", "routes/api.admin.comments.tsx"),
  route("api/admin/comments/:id/flag", "routes/api.admin.comments.$id.flag.tsx"),
  route("api/admin/comments/:id/restrict", "routes/api.admin.comments.$id.restrict.tsx"),
  route("api/admin/reports", "routes/api.admin.reports.tsx"),
  route("api/admin/reports/:id", "routes/api.admin.reports.$id.tsx"),
  route("api/admin/contact", "routes/api.admin.contact.tsx"),
  route("api/admin/contact/:id", "routes/api.admin.contact.$id.tsx"),
  route("api/admin/reviews", "routes/api.admin.reviews.tsx"),
  route("api/admin/reviews/:id", "routes/api.admin.reviews.$id.tsx"),
  route("api/admin/discussions", "routes/api.admin.discussions.tsx"),
  route("api/admin/discussions/:id", "routes/api.admin.discussions.$id.tsx"),
  route("api/admin/blog-posts", "routes/api.admin.blog-posts.tsx"),
  route("api/admin/blog-posts/:id", "routes/api.admin.blog-posts.$id.tsx"),
  route("api/admin/blog-posts/:id/publish", "routes/api.admin.blog-posts.$id.publish.tsx"),
  route("api/admin/movies", "routes/api.admin.movies.tsx"),
  route("api/admin/movies/:id", "routes/api.admin.movies.$id.tsx"),
  route("api/admin/movies/:id/movie-of-the-week", "routes/api.admin.movies.$id.movie-of-the-week.tsx"),
  route("api/admin/upload-image", "routes/api.admin.upload-image.tsx"),
  route("api/movie-of-the-week", "routes/api.movie-of-the-week.tsx"),
  route("api/movies-and-tv-series", "routes/api.movies-and-tv-series.tsx"),
  route("api/reviews", "routes/api.reviews.tsx"),
  route("api/admin/justwatch", "routes/api.admin.justwatch.tsx"),
  route("admin", "routes/admin.tsx", [
    index("routes/admin.index.tsx"),
    route("members", "routes/admin.members.tsx"),
    route("catalog", "routes/admin.catalog.tsx"),
    route("moderation", "routes/admin.moderation.tsx"),
    route("publishing", "routes/admin.publishing.tsx"),
  ]),
  route("user-dashboard", "routes/user-dashboard.tsx"),
  layout("routes/site.tsx", [
    index("routes/home.tsx"),
    route("movie/:slug", "routes/movie.$slug.tsx"),
    route("tv/:slug", "routes/tv.$slug.tsx"),
    route("short/:slug", "routes/short.$slug.tsx"),
    route("movie/:slug/opengraph-image", "routes/og.movie.$slug.ts"),
    route("tv/:slug/opengraph-image", "routes/og.tv.$slug.ts"),
    route("short/:slug/opengraph-image", "routes/og.short.$slug.ts"),
    route("movies-and-tv", "routes/movies-and-tv.tsx"),
    route("scoreboard", "routes/scoreboard.tsx"),
    route("discussions", "routes/discussions.tsx"),
    route("reviews", "routes/reviews.tsx"),
    route("reviews/:id", "routes/reviews.$id.tsx"),
    route("members/:username", "routes/members.$username.tsx"),
    route("about", "routes/about.tsx"),
    route("privacy", "routes/privacy.tsx"),
    route("terms", "routes/terms.tsx"),
    route("contact", "routes/contact.tsx"),
  ]),
] satisfies RouteConfig;
